//#define LOG_OPERATORS_PARSING
using Strict.Language;

namespace Strict.Expressions;

public sealed class Binary(Expression left, Method operatorMethod, Expression[] right)
	: MethodCall(operatorMethod, left, right, null, left.LineNumber)
{
	/// <summary>
	/// For "in" we have to swap left and right (in is always implemented in the Iterator)
	/// </summary>
	public override string ToString() => cachedString ??= BinaryToString();
	private string? cachedString;

	internal string BinaryToString(bool isNot = false) =>
		Method.Name is BinaryOperator.In
			? $"{AddNestedBracketsIfNeeded(Arguments[0])} is "+(isNot?"not ":"")+ $"in {AddNestedBracketsIfNeeded(Instance!)}"
			: $"{
				// Skip 'to Text' for Text concatenations, they won't appear in the input and are autogenerated
				AddNestedBracketsIfNeeded(Method.Name == BinaryOperator.Plus && Instance is To to &&
				to.ConversionType.IsText && Arguments[0].ReturnType.IsText
					? to.Instance!
					: Instance!)
				} {(Method.Name is UnaryOperator.Not || Method.Name is BinaryOperator.Is && isNot
					? "is "
					: "")}{(isNot ? UnaryOperator.Not : Method.Name)} {AddNestedBracketsIfNeeded(Arguments[0], isNot? 10 : 0)}";

	public static Expression Parse(Body body, ReadOnlySpan<char> input, Stack<Range> postfixTokens)
	{
#if LOG_OPERATORS_PARSING
		Console.WriteLine();
		Console.WriteLine("Binary.Parse " + input.ToString() + ", postfixTokens=" + postfixTokens.Count);
#endif
		if (postfixTokens.Count < 3)
			throw new IncompleteTokensForBinaryExpression(body, input, postfixTokens); //ncrunch: no coverage
		ValidateInOperatorUsage(input);
		return BuildBinaryExpression(body, input, postfixTokens.Pop(), postfixTokens);
	}

	private static void ValidateInOperatorUsage(ReadOnlySpan<char> input)
	{
		if (ContainsOutsideText(input, " in ") && !ContainsOutsideText(input, " is in ") &&
			!ContainsOutsideText(input, " is not in "))
			throw new InMustAlwaysBePrecededByIsOrIsNot(input.ToString());
	}

	private static bool ContainsOutsideText(ReadOnlySpan<char> input, string token)
	{
		var isInsideText = false;
		for (var index = 0; index <= input.Length - token.Length; index++)
		{
			if (input[index] == '"' && (index == 0 || input[index - 1] != '\\'))
				isInsideText = !isInsideText;
			if (!isInsideText && input.Slice(index, token.Length).Compare(token))
				return true;
		}
		return false;
	}

	public sealed class IncompleteTokensForBinaryExpression(Body body, ReadOnlySpan<char> input,
		IEnumerable<Range> postfixTokens) : ParsingFailed(body, //ncrunch: no coverage
		string.Join(", ", input.GetTextsFromRanges(postfixTokens).Reverse()));

	private static Expression BuildBinaryExpression(Body body, ReadOnlySpan<char> input,
		Range operatorTokenRange, Stack<Range> tokens)
	{
		var operatorToken = input[operatorTokenRange].ToString();
#if LOG_OPERATORS_PARSING
		Console.WriteLine("BuildBinaryExpression operator=" + operatorToken + ", remaining tokens=" +
			tokens.Count);
#endif
		return operatorToken switch
		{
			BinaryOperator.To => To.Parse(body, input[tokens.Pop()],
				GetUnaryOrBuildNestedBinary(body, input, tokens)),
			UnaryOperator.Not => BuildNotBinaryExpression(body, input, tokens),
			_ => BuildRegularBinaryExpression(body, input, tokens, operatorToken)
		};
	}

	public sealed class InMustAlwaysBePrecededByIsOrIsNot(string input) : Exception(input);

	private static Expression BuildNotBinaryExpression(Body body, ReadOnlySpan<char> input,
		Stack<Range> tokens) =>
		BuildNot(tokens.Count == 1
			? GetUnaryOrBuildNestedBinary(body, input, tokens)
			: BuildRegularBinaryExpression(body, input, tokens, input[tokens.Pop()].ToString()));

	private static Binary BuildRegularBinaryExpression(Body body, ReadOnlySpan<char> input,
		Stack<Range> tokens, string operatorToken)
	{
#if LOG_OPERATORS_PARSING
		Console.WriteLine("BuildRegularBinaryExpression operatorToken=" + operatorToken + ", next token=" +
			input[tokens.Peek()].ToString() + ", remaining tokens=" + tokens.Count);
#endif
		var right = GetUnaryOrBuildNestedBinary(body, input, tokens,
			operatorToken is BinaryOperator.Is);
#if LOG_OPERATORS_PARSING
		Console.WriteLine("BuildRegularBinaryExpression right=" + right + ", next token=" +
			input[tokens.Peek()].ToString() + ", remaining tokens=" + tokens.Count);
#endif
		var left = GetUnaryOrBuildNestedBinary(body, input, tokens);
#if LOG_OPERATORS_PARSING
		Console.WriteLine("BuildRegularBinaryExpression left=" + left + ", next token=" +
			(tokens.Count > 0
				? input[tokens.Peek()].ToString()
				: "<empty>") + ", remaining tokens=" + tokens.Count);
#endif
		// Any incompatibility is checked at runtime when the Executor runs on this
		if (operatorToken is BinaryOperator.In)
			return new Binary(right, right.ReturnType.GetMethod(BinaryOperator.In, [left]), [left]);
		if (operatorToken is BinaryOperator.Plus && !left.ReturnType.IsText &&
			!left.ReturnType.IsList && !left.ReturnType.IsDictionary &&
			right.ReturnType.IsText && !HasMatchingPlusForText(left, right))
			return BuildTextConcatenation(left, right);
		if (operatorToken is BinaryOperator.Plus && left.ReturnType.IsList && right.ReturnType.IsList)
			try
			{
				return new Binary(left, left.ReturnType.GetMethod(operatorToken, [right]), [right]);
			}
			catch (Language.Type.ArgumentsDoNotMatchMethodParameters)
			{
				return new Binary(left,
					left.ReturnType.AvailableMethods[operatorToken].First(method => method.Parameters.Count == 1 &&
						method.Parameters[0].Type.IsList), [right]);
			}
		return new Binary(left, left.ReturnType.GetMethod(operatorToken, [right]), [right]);
	}

	private static bool HasMatchingPlusForText(Expression left, Expression right)
	{
		try
		{
			return left.ReturnType.FindMethod(BinaryOperator.Plus, [right]) != null;
		}
		catch (Language.Type.ArgumentsDoNotMatchMethodParameters)
		{
			return false;
		}
	}

	private static Binary BuildTextConcatenation(Expression left, Expression right) =>
		new(To.ConvertToText(left, right.ReturnType),
			right.ReturnType.GetMethod(BinaryOperator.Plus, [right]), [right]);

	private static Expression GetUnaryOrBuildNestedBinary(Body body, ReadOnlySpan<char> input,
		Stack<Range> tokens, bool checkRightForIsTypeComparison = false)
	{
		var nextTokenRange = tokens.Pop();
#if LOG_OPERATORS_PARSING
		Console.WriteLine("GetUnaryOrBuildNestedBinary token=" +
			input[nextTokenRange].ToString() + ", remaining tokens=" + tokens.Count);
#endif
		return input[nextTokenRange].IsNot()
			? BuildNot(GetUnaryOrBuildNestedBinary(body, input, tokens, checkRightForIsTypeComparison))
			: nextTokenRange.End.Value == nextTokenRange.Start.Value + 1 &&
			input[nextTokenRange.Start.Value].IsSingleCharacterOperator() ||
			input[nextTokenRange].IsMultiCharacterOperator()
				? BuildBinaryExpression(body, input, nextTokenRange, tokens)
				: checkRightForIsTypeComparison
					? TypeComparison.Parse(body, input, nextTokenRange)
					: body.Method.ParseExpression(body, input[nextTokenRange]);
	}

	private static Expression BuildNot(Expression expression) =>
		new Not(expression.ReturnType.GetMethod(UnaryOperator.Not, []), expression);
}