namespace Strict.Language;

public sealed partial class TypeParser
{
	private void TryInitializeMemberInitialValues(ExpressionParser parser)
	{
		try
		{
			foreach (var pair in rememberToInitializeMemberInitialValues!)
				pair.Key.InitialValue =
					GetMemberExpression(parser, pair.Key.Name, pair.Value, pair.Key.LineNumber);
		}
		catch (ParsingFailed)
		{
			type.Dispose();
			throw;
		}
		catch (Exception ex)
		{
			type.Dispose();
			throw new ParsingFailed(type, 0, string.IsNullOrEmpty(ex.Message)
				? ex.GetType().Name
				: ex.Message, ex);
		}
	}

	private Member GetNewMember(ExpressionParser parser, string usedKeyword = Keyword.Has)
	{
		var member = ParseMember(parser, lines[LineNumber].AsSpan(usedKeyword.Length + 1), usedKeyword);
		return type.Members.Any(m => m.Name == member.Name)
			? throw new DuplicateMembersAreNotAllowed(type, LineNumber, member.Name)
			: member;
	}

	private Member ParseMember(ExpressionParser parser, ReadOnlySpan<char> remainingLine,
		string usedKeyword)
	{
		if (type.Methods.Count > 0)
			throw new MembersMustComeBeforeMethods(type, LineNumber, remainingLine.ToString());
		try
		{
			return TryParseMember(parser, remainingLine, usedKeyword);
		}
		catch (ParsingFailed)
		{
			throw;
		}
		catch (Exception ex)
		{
			throw new ParsingFailed(type, LineNumber, ex.Message.Split('\n').Take(2).ToLines(), ex);
		}
	}

	private Member TryParseMember(ExpressionParser parser, ReadOnlySpan<char> remainingLine,
		string usedKeyword)
	{
		var nameAndExpression = remainingLine.Split();
		nameAndExpression.MoveNext();
		var nameAndType = nameAndExpression.Current.ToString();
		if (nameAndType.StartsWith(type.Name.MakeFirstLetterLowercase(), StringComparison.Ordinal))
			throw new MemberNameMustNotStartWithTypeName(type, LineNumber, nameAndType);
		if (nameAndExpression.MoveNext())
		{
			var wordAfterName = nameAndExpression.Current.ToString();
			if (nameAndExpression.Current[0] == EqualCharacter)
			{
				//TODO: this is almost the same code as below in line 520+
				var constantValue = remainingLine[(nameAndType.Length + 3)..];
				var withIndex = constantValue.IndexOf(" " + Keyword.With + " ", StringComparison.Ordinal);
				var valueOnly = withIndex >= 0
					? constantValue[..withIndex]
					: constantValue;
				if (usedKeyword == Keyword.Constant && int.TryParse(valueOnly, out var forcedEnumNumber))
					type.AutogeneratedEnumValue = forcedEnumNumber + 1;
				var member = new Member(type, nameAndType, valueOnly.IsEmpty
					? null
					: GetInitialValueType(parser, nameAndType, valueOnly), LineNumber, usedKeyword)
				{
					InitialValueText = valueOnly.IsEmpty
						? null
						: valueOnly.ToString()
				};
				if (!valueOnly.IsEmpty)
				{
					rememberToInitializeMemberInitialValues ??= new Dictionary<Member, string>();
					rememberToInitializeMemberInitialValues.Add(member, valueOnly.ToString());
				}
				if (withIndex >= 0)
				{
					var constraintsSpan = constantValue[(withIndex + Keyword.With.Length + 2)..];
					pendingConstraints ??= new List<(Member, string[])>();
					pendingConstraints.Add((member,
						constraintsSpan.ToString().Split(BinaryOperator.And, StringSplitOptions.TrimEntries)));
				}
				return member;
			}
			if (wordAfterName != Keyword.With)
			{
				var explicitType = GetMemberType(nameAndExpression);
				if (string.Equals(nameAndType, explicitType, StringComparison.Ordinal) ||
					string.Equals(nameAndType.MakeFirstLetterUppercase(), explicitType,
						StringComparison.Ordinal))
					throw new RedundantExplicitMemberTypeName(type, LineNumber, nameAndType, explicitType);
				nameAndType += " " + explicitType;
			}
			if (HasConstraints(wordAfterName, ref nameAndExpression))
				return !nameAndExpression.MoveNext()
					? throw new MemberMissingConstraintExpression(type, LineNumber, nameAndType)
					: IsMemberTypeAny(nameAndType, nameAndExpression)
						? throw new MemberWithTypeAnyIsNotAllowed(type, LineNumber, nameAndType)
						: GetMemberWithConstraints(parser, remainingLine, usedKeyword, nameAndType);
			if (nameAndExpression.Current[0] == EqualCharacter)
				return ParseTypedMemberWithInitialValue(parser, remainingLine, usedKeyword, nameAndType);
		}
		return IsMemberTypeAny(nameAndType, nameAndExpression)
			? throw new MemberWithTypeAnyIsNotAllowed(type, LineNumber, nameAndType)
			: usedKeyword == Keyword.Constant
				? new Member(type, nameAndType, type.GetType(Type.Number), LineNumber, usedKeyword)
				{
					InitialValue = GetMemberExpression(parser, nameAndType,
						(type.AutogeneratedEnumValue++).ToString(), LineNumber)
				}
				: new Member(type, nameAndType, null, LineNumber, usedKeyword);
	}

	private Type GetInitialValueType(ExpressionParser parser, string nameAndType,
		ReadOnlySpan<char> constantValue)
	{
		if (constantValue.EndsWith(')'))
		{
			var openBracketIndex = constantValue.IndexOf('(');
			if (openBracketIndex > 0 && !constantValue[..openBracketIndex].Contains('.') &&
				constantValue.FindMatchingBracketIndex(openBracketIndex) == constantValue.Length - 1)
			{
				var initialValueTypeName = constantValue[..openBracketIndex];
				return initialValueTypeName == type.Name
					? type
					: type.GetType(initialValueTypeName.ToString());
			}
		}
		// Enum constants are PascalCase and must stay Number/Text/etc. Only camelCase fields
		// named after a type (has character = 48) are upcast to that type.
		if (char.IsLower(nameAndType[0]))
		{
			var memberNameWithFirstLetterCaps = nameAndType.MakeFirstLetterUppercase();
			var memberNameType = FindUpcastType(memberNameWithFirstLetterCaps);
			if (memberNameType != null && !constantValue.StartsWith(memberNameWithFirstLetterCaps))
				return memberNameType;
		}
		if (constantValue.StartsWith('\"'))
			return type.GetType(Type.Text);
		if (constantValue is "true" || constantValue is "false")
			return type.GetType(Type.Boolean); //ncrunch: no coverage
		return constantValue.TryParseNumber(out _)
			? type.GetType(Type.Number)
			: GetMemberExpression(parser, nameAndType, constantValue, LineNumber).ReturnType;
	}

	/// <summary>
	/// Handles "has Name Type = value" syntax where both explicit type and initial value are given.
	/// </summary>
	private Member ParseTypedMemberWithInitialValue(ExpressionParser parser,
		ReadOnlySpan<char> remainingLine, string usedKeyword, string nameAndType)
	{
		var equalIndex = remainingLine.IndexOf(" = ");
		var constantValue = remainingLine[(equalIndex + 3)..];
		var withIndex = constantValue.IndexOf(" " + Keyword.With + " ", StringComparison.Ordinal);
		var valueOnly = withIndex >= 0
			? constantValue[..withIndex]
			: constantValue;
		var member = new Member(type, nameAndType, null, LineNumber, usedKeyword)
		{
			InitialValueText = GetTypedMemberInitializerText(parser, nameAndType, valueOnly)
		};
		rememberToInitializeMemberInitialValues ??= new Dictionary<Member, string>();
		rememberToInitializeMemberInitialValues.Add(member, member.InitialValueText);
		if (withIndex >= 0)
		{
			var constraintsSpan = constantValue[(withIndex + Keyword.With.Length + 2)..];
			pendingConstraints ??= new List<(Member, string[])>();
			pendingConstraints.Add((member,
				constraintsSpan.ToString().Split(BinaryOperator.And, StringSplitOptions.TrimEntries)));
		}
		return member;
	}

	private string GetTypedMemberInitializerText(ExpressionParser parser, string nameAndType,
		ReadOnlySpan<char> valueOnly)
	{
		var declaredTypeName = nameAndType[(nameAndType.IndexOf(' ') + 1)..];
		if (StartsWithConstructorCall(valueOnly, declaredTypeName))
			throw new NamedType.AssignmentWithInitializerTypeShouldNotHaveNameWithSameType(nameAndType);
		var parsedValue = parser.ParseExpression(
			new Body(new Method(type, LineNumber, parser, [nameof(GetMemberExpression)])), valueOnly);
		return parsedValue.ReturnType.Name == declaredTypeName ||
			!HasMatchingFromConstructor(type.GetType(declaredTypeName), parsedValue.ReturnType)
				? valueOnly.ToString()
				: declaredTypeName + "(" + valueOnly.ToString() + ")";
	}

	private static bool HasMatchingFromConstructor(Type declaredType, Type valueType) =>
		declaredType.AvailableMethods.TryGetValue(Method.From, out var fromMethods) &&
		fromMethods.Any(fromMethod => fromMethod.Parameters.Count == 1 &&
			valueType.IsSameOrCanBeUsedAs(fromMethod.Parameters[0].Type));

	private Member GetMemberWithConstraints(ExpressionParser parser, ReadOnlySpan<char> remainingLine,
		string usedKeyword, string nameAndType)
	{
		var member = new Member(type, nameAndType,
			ExtractConstraintsSpanAndValueType(parser, remainingLine, nameAndType,
				out var constraintsSpan, out var initialValueSpan), LineNumber, usedKeyword);
		if (initialValueSpan != "")
		{
			member.InitialValueText = initialValueSpan;
			rememberToInitializeMemberInitialValues ??= new Dictionary<Member, string>();
			rememberToInitializeMemberInitialValues.Add(member, initialValueSpan);
		}
		if (!constraintsSpan.IsEmpty)
		{
			pendingConstraints ??= new List<(Member, string[])>();
			pendingConstraints.Add((member,
				constraintsSpan.ToString().Split(BinaryOperator.And, StringSplitOptions.TrimEntries)));
		}
		return member;
	}

	private List<(Member member, string[] constraintsText)>? pendingConstraints;

	public void ParseDeferredConstraints(ExpressionParser parser)
	{
		if (pendingConstraints == null && rememberToInitializeMemberInitialValues == null)
			return;
		if (pendingConstraints != null)
		{
			foreach (var (member, constraintsText) in pendingConstraints)
				member.ParseConstraints(parser, constraintsText);
			pendingConstraints = null;
		}
		if (rememberToInitializeMemberInitialValues != null)
			TryInitializeMemberInitialValues(parser);
	}

	private Type? ExtractConstraintsSpanAndValueType(ExpressionParser parser,
		ReadOnlySpan<char> remainingLine, string nameAndType, out ReadOnlySpan<char> constraintsSpan,
		out string initialValueSpan)
	{
		var constraintKeywordLength = Keyword.With.Length;
		var equalIndex = FindStandaloneEqualIndex(remainingLine);
		if (equalIndex > 0)
		{
			constraintsSpan =
				remainingLine[(nameAndType.Length + 1 + constraintKeywordLength + 1)..(equalIndex - 1)];
			initialValueSpan = remainingLine[(equalIndex + 2)..].ToString();
			return GetInitialValueType(parser, nameAndType, initialValueSpan);
		}
		constraintsSpan = remainingLine[(nameAndType.Length + 1 + constraintKeywordLength + 1)..];
		initialValueSpan = "";
		return null;
	}

	private static int FindStandaloneEqualIndex(ReadOnlySpan<char> line)
	{
		for (var index = 1; index < line.Length; index++)
			if (line[index] == EqualCharacter && line[index - 1] != '>' && line[index - 1] != '<' &&
				line[index - 1] != '!' && (index + 1 >= line.Length || line[index + 1] != '='))
				return index;
		return -1;
	}

	internal Expression GetMemberExpression(ExpressionParser parser, string memberName,
		ReadOnlySpan<char> remainingTextSpan, int typeLineNumber) =>
		parser.ParseExpression(
			new Body(new Method(type, typeLineNumber, parser, [nameof(GetMemberExpression)])),
			GetFromConstructorCallFromUpcastableMemberOrJustEvaluate(memberName, remainingTextSpan));

	private ReadOnlySpan<char> GetFromConstructorCallFromUpcastableMemberOrJustEvaluate(
		string memberName, ReadOnlySpan<char> remainingTextSpan)
	{
		// Only wrap camelCase fields (has character = 48 → Character(48)). Enum constants such as
		// `constant Add` after `constant StoreSeparator = 10` stay numeric even if a type named
		// Add exists (Add.from often takes two Numbers, so Add(11) would fail to parse).
		if (char.IsLower(memberName[0]))
		{
			var memberNameWithFirstLetterCaps = memberName.MakeFirstLetterUppercase();
			if (FindUpcastType(memberNameWithFirstLetterCaps) != null &&
				!remainingTextSpan.StartsWith(memberNameWithFirstLetterCaps))
				return string.Concat(memberNameWithFirstLetterCaps, "(", remainingTextSpan, ")").AsSpan();
		}
		return remainingTextSpan.StartsWith(type.Name) && !char.IsUpper(memberName[0])
			? throw new CurrentTypeCannotBeInstantiatedAsMemberType(type, LineNumber,
				remainingTextSpan.ToString())
			: remainingTextSpan;
	}

	/// <summary>
	/// Only types of the own package, its parents or a top level (base) package count, an unrelated
	/// package that happens to be loaded must not change a member type (`constant limit = 10`).
	/// </summary>
	private Type? FindUpcastType(string typeName)
	{
		var found = type.FindType(typeName);
		if (found == null || !found.Package.FullName.Contains(Context.ParentSeparator))
			return found;
		for (var package = type.Package; package != null; package = package.Parent as Package)
			if (found.Package == package)
				return found;
		return null;
	}

	public sealed class CurrentTypeCannotBeInstantiatedAsMemberType(Type type,
		int lineNumber,
		string typeName) : ParsingFailed(type, lineNumber, typeName);

	private static string GetMemberType(SpanSplitEnumerator nameAndExpression)
	{
		var memberType = nameAndExpression.Current.ToString();
		while (memberType.Contains('(') && !memberType.Contains(')'))
		{
			nameAndExpression.MoveNext();
			memberType += " " + nameAndExpression.Current.ToString();
		}
		return memberType;
	}

	public sealed class MemberMissingConstraintExpression(Type type,
		int lineNumber,
		string memberName) : ParsingFailed(type, lineNumber, memberName);

	private static bool IsMemberTypeAny(string nameAndType, SpanSplitEnumerator nameAndExpression) =>
		nameAndType == Type.AnyLowercase ||
		nameAndExpression.Current.Equals(Type.Any, StringComparison.Ordinal);

	public sealed class MemberWithTypeAnyIsNotAllowed(Type type, int lineNumber, string name)
		: ParsingFailed(type, lineNumber, name);

	public sealed class MembersMustComeBeforeMethods(Type type, int lineNumber, string line)
		: ParsingFailed(type, lineNumber, line);

	public sealed class DuplicateMembersAreNotAllowed(Type type, int lineNumber, string name)
		: ParsingFailed(type, lineNumber, name);
}
